# setup our env to point to the dotfiles
DOTFILES=~/.dotfiles
ZSH=~/.zsh
ZSH_THEME=default
EDITOR=vim
set -o vi

plugins=(brew cap gem heroku osx p h x tmux)

# load our zsh environment
[[ -f ~/.zsh/init.sh ]] && . ~/.zsh/init.sh

# ---> Local Config

# Custom matcher for my projects colder
#PATH_MATCHERS+=("~/Projects")
#PATH_REPLACER+=("%B%F{yellow}projects%b")

# Custom prompt color
THEME_PROMPT_COLOR="yellow"

# Add user and host before the path
THEME_PATH_BEFORE="%n@%m "

# Used in the `finddir` command
export FINDDIR_SEARCH_PATHS="~/Projects:~/XCode"

# ---> Some common aliases
#alias less='less -R'
#alias -g ls="ls $LS_OPTIONS"
#alias cdd='cd ~/Desktop'
#alias c='cd /usr/local/Cellar'
#alias bc='bundle console'
#alias fm=foreman
#alias fms="foreman start"
#alias bower='noglob bower'
#alias rake='noglob rake'
#alias c='cd /usr/local/Cellar'
#alias grep='pcregrep --color=auto'

# Tmux (use with tmux plugin)
#alias tml="tmux list-sessions"
#alias tma=tmux-attach-or-new
#alias tms=tmux-force-switch
#alias tmd="tmux detach"
#alias tmx="tmux kill-session -t"

# Tig
#alias ts='tig status'
#alias tb='tig blame'
#alias ta='tig --all'
#alias ts='tig status'
#alias tg='tig grep'
#function tl(){
  #$(git log --all --decorate --format='commit %h %an: %s' $* | tig)
#}

# ---> FZF (requires fzf plugin)

# export FUZZY_SEARCH_PATHS="~/Projects:~/XCode:~/Sites/apps:~/Sites/gems:~/Sites"
alias cds=fuzzy-cds
alias co=fuzzy-co
alias eb=fuzzy-bundle-open
alias ef=fuzzy-edit
alias cdf=fuzzy-cd
alias fkill=fuzzy-kill

# ---> Misc

# # Search bundle paths for something
# function back() {
#   ack "$@" `bundle show --paths`
# }

# # Dump pg database
# # Usage: dbdump DBNAME > DUMPFILE
# function dbdump() {
#   DBUSER=${DBUSER:-postgres} # default to postgres
#   pg_dump -Fc --no-acl --no-owner -h localhost -U $DBUSER $@
# }

# # Restore pg database
# # Usage: dbrestore DBNAME < DUMPFILE
# function dbrestore() {
#   DBHOST=${DBHOST:-localhost}
#   DBUSER=${DBUSER:-postgres}
#   pg_restore --verbose --clean --no-acl --no-owner -h $DBHOST -U $DBUSER -d $@
# }
