# setup our env to point to the dotfiles
DOTFILES=~/.dotfiles
ZSH=~/.zsh
ZSH_THEME=default
EDITOR=vim
set -o vi

plugins=(osx tmux fzf)

# load our zsh environment
[[ -f ~/.zsh/init.zsh ]] && . ~/.zsh/init.zsh

# ---> Local Config

# Disable for OSX
# export LS_OPTIONS=''

# Custom matcher for my projects colder
PATH_MATCHERS+=("~/Projects")
PATH_REPLACER+=("%B%F{yellow}projects%b")

# Custom prompt color
THEME_PROMPT_COLOR="yellow"

# Add user and host before the path
THEME_PATH_BEFORE="%n@%m "

# ---> Some common aliases
# alias less='less -R'
# alias -g ls="ls $LS_OPTIONS"
# alias cdd='cd ~/Desktop'
# alias bc='bundle console'
# alias c='cd /usr/local/Cellar'
# alias grep='pcregrep --color=auto'

# Development
# alias e=vim
# alias edf="pushd $DOTFILES && vim && popd"
# alias ev='pushd ~/.dotvim && vim vimrc && popd'
# alias erc='vim ~/.zshrc'
# alias cdg="cd $GOPATH/src/github.com/robhurring"
# alias rsa='auto-bundle-exec rspec -fd'
# alias rs='rsa --fail-fast'
# alias rake="auto-bundle-exec rake"
# alias guard="auto-bundle-exec guard"
# alias pry="auto-bundle-exec pry"

# Tmux (use with tmux plugin)
# alias tml="tmux list-sessions"
# alias tma=tmux-attach-or-new
# alias tms=tmux-force-switch
# alias tmd="tmux detach"
# alias tmx="tmux kill-session -t"

# Tig
# alias ts='tig status'
# alias tb='tig blame'
# alias ta='tig --all'
# alias ts='tig status'
# alias tg='tig grep'
# function tl(){
#   $(git log --all --decorate --format='commit %h %an: %s' $* | tig)
# }

# ---> FZF (requires fzf plugin)

[[ -f ~/.fzf.zsh ]] && source ~/.fzf.zsh

# export FUZZY_SEARCH_PATHS="~/Projects:~/XCode:~/Sites/apps:~/Sites/gems:~/Sites"
# alias cds=fuzzy-cds
# alias co=fuzzy-co
# alias eb=fuzzy-bundle-open
# alias ef=fuzzy-edit
# alias cdf=fuzzy-cd
# alias fkill=fuzzy-kill

# function fzf-fuzzy-cds () {
#   fuzzy-cds $1
#   zle reset-prompt
# }
# zle -N fzf-fuzzy-cds
# bindkey "^ " fzf-fuzzy-cds

# function fzf-fuzzy-co {
#   co
#   zle reset-prompt
# }
# zle -N fzf-fuzzy-co
# bindkey "^b" fzf-fuzzy-co

# ---> Golang
# export GOPATH=$HOME/Go
# export GOBIN=$GOPATH/bin
# export PATH="$PATH:$GOBIN"

# ---> Misc

# # Search bundle paths for something
# function back() {
#   ack "$@" `bundle show --paths`
# }

# # Dump pg database
# # Usage: dbdump DBNAME > DUMPFILE
# function dbdump() {
#   DBUSER=${DBUSER:-postgres} # default to postgres
#   pg_dump -Fc --no-acl --no-owner -h localhost -U $DBUSER $@
# }

# # Restore pg database
# # Usage: dbrestore DBNAME < DUMPFILE
# function dbrestore() {
#   DBHOST=${DBHOST:-localhost}
#   DBUSER=${DBUSER:-postgres}
#   pg_restore --verbose --clean --no-acl --no-owner -h $DBHOST -U $DBUSER -d $@
# }

# export PATH="$PATH:$HOME/.rvm/bin"
# export PATH="$PATH:$DOTFILES/node_modules/.bin"

