# setup our env to point to the dotfiles
DOTFILES=~/.dotfiles
ZSH=~/.zsh
ZSH_THEME=default

plugins=(brew cap gem git-smart h heroku osx p rvm thor bundler)

# load our zsh environment
[[ -f ~/.zsh/init.sh ]] && . ~/.zsh/init.sh

# customize like a mofo!
