# vim:ft=zsh

# ---> system

: ${ZHOME:=${XDG_CONFIG_HOME}/zsh}

[[ -f $ZHOME/zshenv ]] && source $ZHOME/zshenv

# ---> local

# export EDITOR=nvim

# nvim
# export NVIM_TUI_ENABLE_TRUE_COLOR=1
# export NVIM_LISTEN_ADDRESS=/tmp/neovim.sock

# go
# export GOPATH=$HOME/Go
# export GOBIN=$GOPATH/bin
# export PATH="$PATH:$GOBIN"
