: ${EDITOR:="vim"}
: ${TERM:="xterm-256color"}
: ${SHELL:="/usr/local/bin/zsh"}
: ${DISPLAY:=":0"}

export PATH="$HOME/bin:/usr/local/bin:/usr/local/sbin:/usr/X11/bin:$PATH"
export MANPATH="$XDG_DATA_HOME/man:/usr/local/share/man:$MANPATH"

