export PATH="$HOME/bin:/usr/local/bin:/usr/local/sbin:$PATH"
export MANPATH="$XDG_DATA_HOME/man:/usr/local/share/man:$MANPATH"

: ${EDITOR:="vim"}
: ${TERM:="xterm-256color"}
: ${SHELL:="/usr/local/bin/zsh"}

